---
name: Deployment (Auto)
on:
  push:
    branches:
      - auto-deploy

jobs:
  deployment:
    name: Deployment
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/gatsby-deploy.yml@main
    secrets: inherit
    with:
      env: "dev"
      clean: true
      excludeSubfolder: "test, one, two, three"
      index-mode: ""
      NODE_OPTIONS: "--max-old-space-size=8192"